# zsh目录
export ZSH=$HOME/.oh-my-zsh

CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE=true
DISABLE_MAGIC_FUNCTIONS=true
ZSH_THEME="my"

# 插件
plugins=(
  docker
  docker-compose
  extract
  git
  gitfast
  golang
  helm
  kubectl
  rust
  sudo
  urltools
  zoxide
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

autoload -U compinit; compinit

# Golang
export GOPATH="$HOME/go"
export GOBINPATH="$HOME/go/bin"
export GOPROXY=https://goproxy.cn,direct
export GOSUMDB=off

# PATH
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="${GOBINPATH}:${PATH}"
export PATH

# zsh-syntax-highlighting
ZSH_HIGHLIGHT_STYLES[globbing]='fg=yellow'

# disable numeric argument.
for i in {0..9}; do bindkey -r "^[$i"; done

_custom_clear_screen() { clear; date; zle redisplay; }
zle -N _custom_clear_screen
bindkey '^L' _custom_clear_screen

ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;'

# history
export HISTSIZE=100000
export SAVEHIST=100000

# 搜索
bindkey '^p' up-line-or-beginning-search
bindkey '^n' down-line-or-beginning-search

bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

# proxy
_toggle_proxy() {
    if [[ -n "${http_proxy}" ]] || [[ -n "${http_proxy}" ]]; then
        unset http_proxy https_proxy
    else
        export http_proxy="http://192.168.56.1:7890"
        export https_proxy="http://192.168.56.1:7890"
        export no_proxy="localhost,127.0.0.1"
    fi

    zle reset-prompt
}
zle -N _toggle_proxy
bindkey '^[OP' _toggle_proxy

# fzf
export FZF_DEFAULT_COMMAND='fd --type file'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# rg
export RIPGREP_CONFIG_PATH="$HOME/.rgrc"

# tldr
alias tldr='tldr -t ocean'

# vim
alias vi='nvim'
alias vim='nvim'
export MANPAGER='nvim +Man!'
export EDITOR='nvim'
export KUBE_EDITOR=nvim

alias vimyaml='vim -c "set filetype=yaml" -'

# system
case "$OSTYPE" in
  linux*)   source ~/myconfig/zsh/zshrc_linux ;;
  darwin*)  source ~/myconfig/zsh/zshrc_mac ;;
esac

# work env
[ -f ~/.work.zsh ] && source ~/.work.zsh
