# zsh目录
export ZSH=$HOME/.oh-my-zsh

# 补全大小写敏感
CASE_SENSITIVE="true"
# 粘贴修正
DISABLE_MAGIC_FUNCTIONS=true

DISABLE_AUTO_UPDATE=true

# 主题
ZSH_THEME="my"

# 插件
plugins=(
  git
  gitfast
  docker docker-compose
  golang
  pip
  sudo
  extract
  ripgrep
  kubectl
  helm
  urltools
  zoxide
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

autoload -U compinit; compinit

# Golang
export GOPATH="$HOME/go"
export GOBINPATH="$HOME/go/bin"
export GOPROXY=https://goproxy.cn,direct
export GO111MODULE=on
export GOSUMDB=off

# PATH
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="${GOBINPATH}:${PATH}"
export PATH

# zsh-syntax-highlighting
ZSH_HIGHLIGHT_STYLES[globbing]='fg=yellow'

# disable numeric argument.
for i in {0..9}; do bindkey -r "^[$i"; done

_custom_clear_screen() { clear; date; zle redisplay; }
zle -N _custom_clear_screen
bindkey '^L' _custom_clear_screen

ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;'

# history
export HISTSIZE=1000000
export SAVEHIST=1000000

# 搜索
bindkey '^p' up-line-or-beginning-search
bindkey '^n' down-line-or-beginning-search

bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

# fzf
export FZF_DEFAULT_COMMAND='fd --type file'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# rg
export RIPGREP_CONFIG_PATH="$HOME/.rgrc"

# tldr
alias tldr='tldr -t ocean'

# vim
alias vim='nvim'
alias vi='nvim'
export MANPAGER='nvim +Man!'
export EDITOR='nvim'
export KUBE_EDITOR=nvim

alias vimyaml='vim -c "set filetype=yaml" -'

# git
alias gdn='git diff --name-only origin/master'

# system
case "$OSTYPE" in
  linux*)   source ~/myconfig/zsh/zshrc_linux ;;
  darwin*)  source ~/myconfig/zsh/zshrc_mac ;;
esac

# work env
[ -f ~/.work.zsh ] && source ~/.work.zsh
